import LinkSignin from "@/components/linkSignin";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, auth, params: { locale } }) {
  return (
    <html lang={locale}>
      <body
        className={`flex min-h-screen flex-col items-center justify-between p-24`}
      >
        {children}

        <LinkSignin locale={locale} />

        {auth}
      </body>
    </html>
  );
}
