import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// NOTE: I updated the version of nextjs to rc just for the purpose of testing,
// in the end I realized that it had nothing to do with the problem at all
// and that the only problem is the ISR rendering with generateStaticParams

// here is the problem, if I don't use generateStaticParams it works as expected
export async function generateStaticParams() {
  return [{ locale: "es", locale: "en" }];
}

export default function RootLayout({
  children,
  modal1,
  modal2,
  params: { locale },
}) {
  return (
    <html lang={locale}>
      <body
        className={`flex min-h-screen flex-col items-center justify-center gap-4 p-24`}
      >
        {children}

        <Link
          className="bg-slate-400 rounded-md px-4 py-2"
          href={`/${locale}/page1`}
        >
          1- Client Example
        </Link>

        {/* Another problem that I have noticed is that the loading file does not work */}
        <Link
          className="bg-slate-400 rounded-md px-4 py-2"
          href={`/${locale}/page2`}
        >
          2- Server Example
        </Link>

        {modal1}

        {modal2}
      </body>
    </html>
  );
}
